#ifndef CMAKECM_LIB_CMAKECM_LIB_H
#define CMAKECM_LIB_CMAKECM_LIB_H

#define _CMAKECM_LIB_STR0(X) #X
#define _CMAKECM_LIB_STR(X) _CMAKECM_LIB_STR0(X)

#define CMAKECM_LIB_VERSION 1.0.1
#define CMAKECM_STR_LIB_VERSION _CMAKECM_LIB_STR(CMAKECM_LIB_VERSION)

#endif // CMAKECM_LIB_CMAKECM_LIB_H
